# Generated by Django 5.1.1 on 2024-09-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quran_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quran',
            name='discount',
        ),
        migrations.AlterField(
            model_name='quran',
            name='publisher',
            field=models.CharField(default='No Publisher', max_length=255),
        ),
        migrations.AlterField(
            model_name='quran',
            name='stock',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='quran',
            name='type',
            field=models.CharField(default='Tafsir', max_length=255),
        ),
    ]
